### ISSUE TITLE
Inquiry about the ground truth CSV

### ISSUE THREAD

**Issue by ganler** [favyen/miris#6]
@uakfdotb  Thanks for your great work.

I am wondering:
1. what do the columns in https://github.com/favyen/miris/blob/master/data/shibuya.csv means?
2. Do you have other ground-truth CSVs and how to compute them?

Thanks!

**Comment by uakfdotb** [comment]
These correspond to different turning directions defined in predicate/tmc.go. The frames column is the range of frames the count covers, e.g., the second row says 1 car turned from bottom to top during first 500 frames.

There seem to be some missing CSVs, I will check it.

**Comment by ganler** [comment]
Thanks!
