### ISSUE TITLE
Meanings of blank lists in final.csv

### ISSUE THREAD

**Issue by ganler** [favyen/miris#7]
Hi @uakfdotb , I wonder if the blank lists are finally filtered frames (i.e., frames we don't need to pay detection) in miris? 

![image](https://user-images.githubusercontent.com/38074777/100195000-a4387b00-2f31-11eb-8530-a63d014508c1.png)

**Comment by uakfdotb** [comment]
These are frames that the method chose not to process. In `eval.go` the tracks are interpolated using linear interpolation to compute positions of objects in intermediate frames. Note that the Acceleration refinement method processes additional frames when it thinks linear interpolation could have higher error (in the case that the object is under a high acceleration/deceleration).
