### ISSUE TITLE
About baselines？

### ISSUE THREAD

**Issue by zhangzhongshuai** [favyen/miris#9]
In the YTStream dataset，“data/beach/json: contains the object tracks computed via a baseline object tracking algorithm for the training and validation video segments. ”

In the paper,"MIRIS: Fast Object Track Queries in Video" (SIGMOD 2020),the baselines of object tracking algorithm included Overlap,PP,KCF,and FlowNet.

I wonder, which baseline object tracking algorithm calculated the tracks recorded in these json files?

![baselines](https://user-images.githubusercontent.com/19491183/103451959-3e47cc00-4d05-11eb-873e-5afe6fd04544.png)

**Comment by uakfdotb** [comment]
These tracks are computed using Overlap at the native video framerate. KCF tries to provide a higher accuracy at lower sampling rates (by processing intermediate frames to update object positions without applying the object detector), but doesn't provide a clear benefit at the native framerate. FlowNet and PP apply models trained using tracks produced by Overlap.
